mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('study/', include('study.urls', namespace='study'))
]

mysite/study/urls.py
from django.urls import path
from . import views

app_name = 'study'

urlpatterns = [
    path('', views.StudyListView.as_view(), name='set_collection'),
    path('<slug:slug>/', views.view_cards, name='view_cards'),
    path('<int:set_id>/add/', views.make_card, name='make_card')
]

mysite/study/models.py
from django.db import models
from django.urls import reverse

#Sets
#take all sets that has more than 5 cards in them
class CanUseManager(models.Manager):
    def get_queryset(self):
        return (
            super().get_queryset().filter(card_amount__gt=5)
        )
    
class Set(models.Model):
    name = models.CharField(max_length=100)
    card_amount = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=100, unique_for_date='created')

    # Managers
    objects = models.Manager()
    # custum managers
    # only sets with more than 5 cards
    can_use = CanUseManager()
    
    class Meta:
        ordering = ['name']
   
    # 
    def get_absolute_url(self):
        return reverse(
            'study:view_cards', 
            args=[
                self.slug
                ]) 
    
    def __str__(self):
        return f"Name: {self.name} Amount of Cards: {self.card_amount}"

#Cards
class Card(models.Model):
    question = models.CharField(max_length=500)
    answer = models.CharField(max_length=500)
    false_answer_1 = models.CharField(max_length=500)
    false_answer_2 = models.CharField(max_length=500)
    false_answer_3 = models.CharField(max_length=500)
    set = models.ForeignKey(
        Set,
        on_delete = models.CASCADE,
        related_name = 'cards'
    )

    # managers
    objects = models.Manager()
    
    def __str__(self):
        return f"Question: {self.question} | Answer: {self.answer}"

mysite/study/forms.py
from django import forms
from .models import Card

class MakeCardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ['question', 'answer', 'false_answer_1', 'false_answer_2', 'false_answer_3']

mysite/study/views.py
from django.shortcuts import get_object_or_404, render
from .models import Set, Card
from .forms import MakeCardForm
from django.views.decorators.http import require_POST
from django.views.generic import ListView

# Display all sets you own
class StudyListView(ListView):
    queryset =  Set.can_use.all()
    context_object_name = 'sets'
    # will change later
    paginate_by = 12
    template_name = 'study/collection/collection.html'

# review the flashcards
def view_cards(request, slug):
    selected_set = get_object_or_404(Set, slug=slug)
    cards = selected_set.cards.all()
    
    return render(
        request,
        'study/collection/viewCards.html',
        {
            'set': selected_set,
            'cards': cards,
        }
    )

# Make a new Card
def make_card(request, set_id):
    set = get_object_or_404(
        Set,
        id=set_id,
    )

    card = None

    if request.method == 'POST':
        form = MakeCardForm(data=request.POST)
        if form.is_valid():
            # unsaved comment
            card = form.save(commit=False)
            #assing set to the comment
            card.set = set
            #save the comment
            card.save()    
    else:
        form = MakeCardForm()
    return render(
        request,
        'study/collection/makeCard.html',
        {
            'set': set,
            'form': form
        },
    )

mysite/study/templates/pagination.html
<div class="pagination">
    <span class="step-links"> 
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

mysite/study/templates/study/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/study.css" %}">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

mysite/study/templates/study/collection/collection.html
{% extends "study/base.html" %}

{% block title %}Your Collection{% endblock %}


{% block content %}
    <!-- Display every set you own -->
    <div class="collection">
    {% for set in sets %}
        <div class="set">
            <h4><a href="{{ set.get_absolute_url }}">{{set.name}}</a></h4>
            <h6>{{set.card_amount}}</h6>
        </div> 
    {% endfor %}
    </div>
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

mysite/study/templates/study/collection/makeCard.html
{% extends "study/base.html" %}
 
{% block title %}Create New Card{% endblock %}

{% block content %}
    <div class="outerForm">
    {% if sent %}
        <h2>Successfully Made A New Card</h2>
    {% else %}
        <h2>Making New Card In {{ set.name }} Set</h2>
        <form action="{% url "study:make_card" set.id %}" method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Submit">
        </form>
    {% endif %}
    </div>
{% endblock %}

mysite/study/templates/study/collection/viewCards.html
{% extends "study/base.html" %}

{% block title %}{{ set.name }}{% endblock %}

{% block content %}
    <p>
        <a href="{% url "study:make_card" set.id %}">Make New Card</a>
    </p>
    <!-- Display each card in the set with its question and correct answer -->
    {% for card in cards %}
        <div class="card">
            <h4>Question: {{card.question}} </h4>
            <h4>Answer: {{card.answer}} </h4>
        </div> 
    {% endfor %}
{% endblock %}